management:
  endpoint:
    # health端点设置
    health:
      # 是否开启
      enabled: true
      # 是哦福显示详细信息
      show-details: always
  health:
    # DiskSpaceHealthIndicator配置项，超过阈值则健康为不可用
    diskspace:
      enabled: true
      # 磁盘路径
      path: .
      # 阈值
      threshold: 1000000
  endpoints:
    # Actuator HTTP 配置项，对应 WebEndpointProperties 配置类
    web:
      base-path: /actuator
      exposure:
        # 需要开放的端口，默认只是health info两个端点
        include: '*'
        # 在include基础上，排除的端点
        # exclude: