management:
  endpoint:
    # metrics端点配置 MetricsProperties配置类
    metrics:
      # 是否开启，默认开启
      enabled: true
  metrics:
    # 指定前缀指标是否开启
    enable:
      xxx: false
    # 通用 tag
    tags:
      application: actuator-demo


  endpoints:
    # Actuator HTTP 配置项，对应 WebEndpointProperties 配置类
    web:
      base-path: /actuator
      exposure:
        # 需要开放的端口，默认只是health info两个端点
        include: '*'
        # 在include基础上，排除的端点
        # exclude: