spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bsk?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:com/jw/**/mapper/*Mapper.xml
  type-aliases-package: com.jw.**.entity