version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - -Djute.maxbuffer=102400000
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://122.112.232.162:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=122.112.232.162:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka-manager:
    image: 'sheepkiller/kafka-manager:latest'
    container_name: kafka-manager
    ports:
      - '9000:9000'
    environment:
      - ZK_HOSTS=122.112.232.162:2181
    depends_on:
      - zookeeper